---
# tasks file for ansible-role-openio-netdata
---

    - package:
        name: netdata
        state: present

    - name: Get all OpenIO RAW-X services configured
      shell: ls -d /etc/oio/sds/VCFR*/rawx-*
      register: rawxlogs
      become: true
    - name: Configure OpenIO RAW-X services log file monitoring
      blockinfile:
        dest: /etc/netdata/python.d/web_log.conf
        block: |
           {{ item | regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}-{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)', '\1') }}:
             name: '.openio.{{ item | regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}.rawx.{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)', '\1') }}.log.access'
             path: '/var/log/oio/sds/{{ item | regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}/{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)', '\1') }}/{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)', '\1') }}-httpd-access.log'
             custom_log_format:
               pattern: '\S+ \S+ \S+ \S+ \S+ \d+ \d+ \S+ \S+ (?P<address>\S+) \S+ (?P<method>\S+) (?P<code>\d+) (?P<resp_time>\d+) (?P<bytes_sent>\d+) \S+ \S+ (?P<url>.*)'
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
      with_items: "{{ rawxlogs.stdout_lines }}"
      become: true
    - name: Get all OpenIO directory services configured
      shell: ls -d /etc/oio/sds/VCFR*/meta*
      register: metalogs
      become: true
    - name: Configure OpenIO directory services log file monitoring
      blockinfile:
        dest: /etc/netdata/python.d/web_log.conf
        block: |
          {{ item | regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}-{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)/.*', '\1') }}:
            name: '.openio.{{ item | regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}.{{ item | regex_replace('/etc/oio/sds/\w+/(\w+)-\w+/.*', '\1') }}.{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)/.*', '\1') }}.log.access'
            path: '/var/log/oio/sds/{{ item | regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}/{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)/.*', '\1') }}/{{ item | regex_replace('/etc/oio/sds/\w+/(\w+-\w+)/.*', '\1') }}.access'
            custom_log_format:
              pattern: '\S+ \S+ \S+ \S+  \S+ \S+ \S+ \S+ (?P<address>\S+) \S+ (?P<method>\S+) (?P<code>\d+) (?P<resp_time>\d+) (?P<bytes_sent>\d+) \S+ \S+ \S+ (?P<url>.*)'
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
      with_items: "{{ metalogs.stdout_lines }}"
      become: true

    - name: Restart netdata
      service:
        name: netdata
        state: restarted
      become: true
