---
# tasks file for ansible-role-openio-netdata

- name: "Configure repositories for {{ ansible_os_family }} distribution"
  tags:
    - install
  include : "{{ ansible_os_family }}.yml"

- name: 'Netdata: Install packages'
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ netdata_packages }}"

# A filter would be much better here @cdelgehier ;-)
- name: Register OpenIO RAW-X services configured
  shell: ls -d /etc/oio/sds/*/rawx-*||true
  register: netdata_openio_rawxlogs
  changed_when: false
- name: Register OpenIO directory services configured
  shell: ls -d /etc/oio/sds/*/meta*||true
  register: netdata_openio_metalogs
  changed_when: false
- name: Creating service list to monitor
  set_fact:
    netdata_openio_service_rawx: |
      [{% for item in netdata_openio_rawxlogs.stdout_lines -%}
        ["{{ item| regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/(\w+)-\w+', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/\w+-(\w+)', '\1') }}"],
      {%- endfor %}]
    netdata_openio_service_meta: |
      [{% for item in netdata_openio_metalogs.stdout_lines -%}
        ["{{ item| regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/(\w+)-\w+', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/\w+-(\w+)', '\1') }}"],
      {%- endfor %}]

- name: 'Netdata: Set configurations'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode:  0644
  with_items:
    - { src: "{{ netdata_global_conf_template }}", dest: "{{ netdata_global_conf_path }}" }
    - { src: "{{ netdata_weblog_conf_template }}", dest: "{{ netdata_weblog_conf_path }}" }
    - { src: "{{ netdata_python_d_conf_template }}", dest: "{{ netdata_python_d_conf_path }}" }
    - { src: "{{ netdata_apps_groups_conf_template }}", dest: "{{ netdata_apps_groups_conf_path }}" }
  notify:
    - restart netdata

- name: 'Netdata: Start service'
  service:
    name: "{{ netdata_service_name }}"
    state: started
    enabled: true
