---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure service is started
  service:
    name: "{{ openio_netdata_service_name }}"
    state: started
    enabled: true

- name: Add user netdata to openio group
  user:
    name: "{{ netdata_user }}"
    groups: openio
    append: true
  when: openio_netdata_oio_host

- name: Register openio services
  include_tasks: openio.yml
  when: openio_netdata_oio_host

- name: 'Set global configuration'
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: "{{ netdata_user }}"
    group: "{{ netdata_group }}"
    mode: 0640
  notify: restart netdata

- name: 'Set plugin configuration'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ netdata_user }}"
    group: "{{ netdata_group }}"
    mode: 0640
  when:
    - openio_netdata_oio_host
    - openio_netdata_python_d_plugin_enabled
  with_items:
    - src: web_log.conf.j2
      dest: /etc/netdata/python.d/web_log.conf
    - src: python.d.conf.j2
      dest: /etc/netdata/python.d.conf
    - src: apps_groups.conf.j2
      dest: /etc/netdata/apps_groups.conf
    - src: beanstalk.conf.j2
      dest: /etc/netdata/python.d/beanstalk.conf
    - src: redis.conf.j2
      dest: /etc/netdata/python.d/redis.conf
  notify: restart netdata
...
