---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure service is started
  service:
    name: "{{ openio_netdata_service_name }}"
    state: started
    enabled: true

- name: Add user netdata to openio group
  user:
    name: "{{ netdata_user }}"
    groups: openio
    append: true
  when: openio_netdata_openio_host

- name: Register openio services
  include_tasks: openio.yml
  when: openio_netdata_openio_host

- name: 'Set global configuration'
  template:
    src: netdata.conf.j2 
    dest: /etc/netdata/netdata.conf
    owner: "{{ netdata_user }}"
    group: "{{ netdata_group }}"
    mode: 0640
  notify: restart netdata

- name: 'Set plugin configuration'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ netdata_user }}"
    group: "{{ netdata_group }}"
    mode: 0640
  when: netdata_python_d_plugin_enabled
  with_items:
    - src: "{{ netdata_weblog_conf_template }}"
      dest: "{{ netdata_weblog_conf_path }}"
    - src: "{{ netdata_python_d_conf_template }}"
      dest: "{{ netdata_python_d_conf_path }}"
    - src: "{{ netdata_apps_groups_conf_template }}"
      dest: "{{ netdata_apps_groups_conf_path }}"
    - src: "{{ netdata_beanstalk_conf_template }}"
      dest: "{{ netdata_beanstalk_conf_path }}"
    - src: "{{ netdata_redis_conf_template }}"
      dest: "{{ netdata_redis_conf_path }}"
  notify: restart netdata
...
