---
- name: Disable fs plugin
  file:
    path: "{{ openio_netdata_plugins_directory }}/fs.plugin"
    state: file
    mode: 0644

- name: Create instances of fs plugin
  copy:
    src: "{{ openio_netdata_plugins_directory }}/fs.plugin"
    dest: "{{ openio_netdata_plugins_directory }}/fs-{{ index }}.plugin"
    mode: 0755
    remote_src: true
  loop: "{{ openio_netdata_oiofs_endpoints | flatten(levels=1) }}"
  loop_control:
    index_var: index
  when: openio_netdata_oiofs_monitor

- name: Fetch all current instances
  find:
    paths: "{{ openio_netdata_plugins_directory }}"
    patterns: fs-*.plugin
  register: to_delete
  when: not openio_netdata_oiofs_monitor

- name: Bulk remove inactive instances
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ to_delete.files }}"
  when: not openio_netdata_oiofs_monitor

- name: Selectively remove inactive instances
  file:
    path: "{{ openio_netdata_plugins_directory }}/fs-{{ index }}.plugin"
    state: absent
  loop: "{{ openio_netdata_oiofs_endpoints | selectattr('enabled', 'equalto', false) | flatten(levels=1) }}"
  loop_control:
    index_var: index
  when: openio_netdata_oiofs_monitor
...
